---
# tasks file for roles/lab12-milestones
- name: Gather datastores configured in {{ vcenter_hostname }}
  community.vmware.vmware_datastore_info:
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    validate_certs: "{{ validate_certs }}"
    datacenter_name: '{{ datacenter_name }}'
  delegate_to: localhost
  register: datastore_info

- name: Check if datastore cluster {{ datastore_cluster_name }} exists and has {{ datastore_count }} datastores in {{ vcenter_hostname }}
  assert:
    that: "{{ datastore_info.datastores | selectattr('datastore_cluster', 'equalto', datastore_cluster_name) | list | length }} == datastore_count"
  ignore_errors: true